### ISSUE TITLE
trying to use this operator as a dependency for another operator

### ISSUE THREAD

**Issue by ryandawsonuk** [Maistra/istio#119] opened 2020-06-15 18:23 UTC
I want to automatically install a service mesh control plane and member roll when the operator I'm working on installs an instance. This is through openshift marketplace/operatorhub. The operator I'm working on is https://github.com/SeldonIO/seldon-deploy-operator

But I find that installing the ServiceMeshControlPlane and ServiceMeshMemberRoll through another operator has some limitations. 

Installing them on the command line and I can install the control plane and then wait until the pods in istio-system are up and install the other and that works. The wait seems to be necessary or else the ServiceMeshMemberRoll never gets a status and any members I add to it don't get registered in the mesh.

So I need a similar wait condition in the automated install. I can do that by adding a helm hook with a sleep in it. But once all the istio objects are created then istio somehow blocks the operator itself from creating further resources:
```
{"level":"error","ts":1592242827.2561026,"logger":"helm.controller","msg":"Release failed","namespace":"seldon","name":"example-seldondeploy","apiVersion":"machinelearning.seldon.io/v1alpha1","kind":"SeldonDeploy","release":"example-seldondeploy","error":"failed to install release: failed post-install: warning: Hook post-install seldon-deploy/templates/openshift-istio.yaml failed: admission webhook \"smmr.validation.maistra.io\" denied the request: user 'system:serviceaccount:openshift-operators:seldon-deploy-operator' does not have permission to access namespace(s): [seldon]"
```
That doesn't happen from the command line. The extra-weird thing is that post-install hook isn't even trying to install anything in the seldon namespace, at least not directly. It's trying to create a ServiceMeshMemberRoll in the istio-system namespace and mark the seldon namespace as a member. I guess I am not creating any default member roll at that point. Not sure what it does when there is no member roll.

Any ideas on what could be going on here or what I might be able to do to work around it?

**Comment by tmckayus** [comment] 2020-06-15 21:16
I *think* the issue here might be that the serviceaccount needs permissions to add a label to the project (maistra.io/member-of)

this may do the trick, added to permissions in the CSV (hmm might need get or list as well depending on how the code adding the label is working. Maybe just start with * and back it off)

```
  - apiGroups:
          - project.openshift.io
          resources:
          - projects
          verbs:
          - update
          - patch
```

**Comment by dgn** [comment] 2020-06-16 09:09
The issue is that when you're editing the ServiceMeshMemberRoll, the Maistra operator's ValidatingWebhook will make sure that the user editing it (in this case this seems to be your ServiceAccount `seldon-deploy-operator`) has `update` permissions on Pods in the namespace that you're trying to add. The reason for this is that adding a namespace potentially means injecting containers into pods.

Granting your ServiceAccount permission to update pods in that namespace should be sufficient:

```yaml
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - update
```

Also, very happy to see you're using the Maistra operator for the seldon project!

**Comment by ryandawsonuk** [comment] 2020-06-16 15:18
Actually I've realised there's a different problem which is actually more of an issue for us. I had missed that to get back to a fresh state I had to [remove the istio CRDs manually](https://docs.openshift.com/container-platform/4.3/service_mesh/service_mesh_install/removing-ossm.html#ossm-remove-cleanup_removing-ossm). Now I see that these CRDs like Gateway and VirtualService are only created when a ServiceMeshControlPlane instance is created.

This imposes a limitation for us as we are installing our operator [as a helm operator](https://github.com/SeldonIO/seldon-deploy-operator) and we have Gateway and VirtualService resources in our manifest. I was hoping we could create the ServiceMeshControlPlane in a helm pre-install hook but by then it is already too late. Helm [checks that it can build the objects in the manifest](https://github.com/helm/helm/blob/e672a42efae30d45ddd642a26557dcdbf5a9f5f0/pkg/action/install.go#L256) before it [executes any pre-install hooks](https://github.com/helm/helm/blob/e672a42efae30d45ddd642a26557dcdbf5a9f5f0/pkg/action/install.go#L326). The sequence is pretty clear in the helm go code as line 256 and 326 of the Run function in install.go.

So now I've got a fresh cluster state with just the mesh operator and no control plane and I run the seldon deploy chart with a helm hook to create the control plane... and I get this helm error:
```
unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"]
```
Helm does have a mechanism to install [CRDs in a crds folder](https://github.com/helm/helm/blob/e672a42efae30d45ddd642a26557dcdbf5a9f5f0/pkg/action/install.go#L185) ahead of the resource checks. So we could consider putting those CRDs in our chart and then presumably they would be created and then later overwritten by the control plane installation.

Otherwise we will just have to tell users to install both the mesh operator and a control themselves by following the [mesh install instructions](https://docs.openshift.com/container-platform/4.3/service_mesh/service_mesh_install/installing-ossm.html#ossm-control-plane-deploy_installing-ossm).

(FWIW before I hit this latest problem I tried assigning cluster-admin to the service account and then I was able to create the servicemeshmemberroll. So it's definitely a permissions problem. Not been able to determine exactly which permission as I'm now dealing with this new issue.)

**Comment by dgn** [comment] 2021-01-19 10:34
Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)

**Closed as completed by dgn** 2021-01-19 10:34 UTC
