### ISSUE TITLE
IPVLAN interface is not being created while sidecar is injected

### ISSUE THREAD

**Issue by gnu300** [Maistra/istio#107] opened 2020-05-07 09:37 UTC
**Bug description**

I am having an issue with OpenShift ServiceMesh 1.1.0 (Maistra, Istio) in combination with pods that have or should have an additionalNetwork with IPVLAN. Without the sidecar injection the additional IPVLAN interface is being created, with the sidecar annotation on the pod the sidecar is being created but the IPVLAN interface (=additional network annotation) is gone.

I am not sure if this expected, i could not find any hint in the documentation that IPVLAN/MACVLAN interfaces are not supported while the sidecar is injected. Does it anyhow relate to https://github.com/Maistra/istio/pull/26 / https://issues.redhat.com/projects/MAISTRA/issues/MAISTRA-518 ?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ X ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The expected behaviour is that while the sidecar is injected the IPVLAN interface is also being created.

**Steps to reproduce the bug**

In order to attach the additional interface to pod you have to annotate the pod accordingly.[1] In my case the needed annotation is "k8s.v1.cni.cncf.io/networks: ipvlan-net". Note that the sidecar injection is disabled:
```
apiVersion: v1
kind: Pod
metadata:
    name: ip-pod
labels:
    app: ip
annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-net
    sidecar.istio.io/inject: "false"
spec:
  containers:
    - resources:
      name: ip-container
      image: nginxinc/nginx-unprivileged
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP
}
```

This creates the pod with the additional IPVLAN interface:

```
~ $ oc rsh -c ip-container  ip-pod1
~ $ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
inet 127.0.0.1/8 scope host lo
valid_lft forever preferred_lft forever
inet6 ::1/128 scope host
valid_lft forever preferred_lft forever
3: eth0@if31: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP
link/ether 0a:58:0a:83:00:16 brd ff:ff:ff:ff:ff:ff
inet 10.131.0.22/23 brd 10.131.1.255 scope global eth0
valid_lft forever preferred_lft forever
inet6 fe80::1091:8eff:fefe:658a/64 scope link
valid_lft forever preferred_lft forever
4: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UNKNOWN
link/ether 00:1a:4a:16:01:e0 brd ff:ff:ff:ff:ff:ff
inet 10.10.10.10/24 brd 10.10.10.255 scope global net1
valid_lft forever preferred_lft forever
inet6 fe80::1a:4a00:116:1e0/64 scope link
valid_lft forever preferred_lft forever
```

The next step is to enable the sidecar injection and re-create the pod. The creation of the pod and the sidecar is successful but the IPVLAN interface is not being created. In fact the sidecar injection process removes the "k8s.v1.cni.cncf.io/networks: ipvlan-net" annotation and puts it in another field:

```kind: Pod
apiVersion: v1
metadata:
  generateName: ip-pod1
  annotations:
    k8s.v1.cni.cncf.io/networks: v1-1-istio-cni
    k8s.v1.cni.cncf.io/networks-status: ''
    openshift.io/scc: restricted
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/status: >-  {"version":"773f050195566e10249458ebfe7cbc78e3fd9b728f7fdeaa355ab0cbe171fc2a","initContainers":null,"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}
....
....  
    - name: ISTIO_METAJSON_ANNOTATIONS
      value: >
        {"k8s.v1.cni.cncf.io/networks":"[ { \"name\": \"ipvlan-net\" }
        ]","openshift.io/scc":"restricted","sidecar.istio.io/inject":"true"}  
....
```
As a result the additional IPVLAN interface is not being created:

```~ $ oc rsh -c ip-container  ip-pod1
~ $ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever
3: eth0@if39: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP link/ether 0a:58:0a:83:00:1e brd ff:ff:ff:ff:ff:ff inet 10.131.0.30/23 brd 10.131.1.255 scope global eth0 valid_lft forever preferred_lft forever inet6 fe80::e0c2:5ff:fe51:b360/64 scope link valid_lft forever preferred_lft forever
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

$ istioctl version              
client version: 1.5.1
control plane version: OSSM_1.1.0
data plane version: maistra-1.1.0

$ oc version                                                                                                  
Client Version: 4.3.8
Server Version: 4.3.13
Kubernetes Version: v1.16.2

**How was Istio installed?**

OpenShift ServiceMesh Operator 1.1.0 

**Environment where bug was observed (cloud vendor, OS, etc)**

OpenShift 4.3.13

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by luksa** [comment] 2020-05-07 09:50
Hi @gnu300, thanks for reporting the bug. 

Any chance you can file an issue in our Jira (https://issues.redhat.com/projects/MAISTRA). If not, I'll do it. 

We have become aware of this issue a week ago. It is caused by the sidecar injector, as it has to set the `k8s.v1.cni.cncf.io/networks` annotation to enable the `istio-cni` CNI plugin. But when it does this, it overrides the existing value of that annotation. We'll need to figure out a way of adding an additional entry into the existing annotation, but it's not as straightforward as it might seem, because you now need to figure out what's the correct order.

As a workaround, you can modify the `istio-sidecar-injector` configmap in the `istio-system` namespace (or wherever you've installed the control plane). Look for the `injectedAnnotations` field inside the `config` entry of the configmap. Of course, this workaround is only applicable if you want all your pods with the Istio sidecar to have the `ipvlan-net` plugin enabled.

**Comment by luksa** [comment] 2020-05-07 09:57
Actually, no need to create the issue in Jira, as we already have it: https://issues.redhat.com/browse/MAISTRA-1374

**Comment by gnu300** [comment] 2020-05-07 10:08
Awesome, thank you for your quick response! I actually did already create an Jira issue, https://issues.redhat.com/projects/MAISTRA/issues/MAISTRA-1432 . I'll close it as duplicate and refer to https://issues.redhat.com/browse/MAISTRA-1374 .
I'll try your workaround in the next hours and give you feedback!

**Comment by luksa** [comment] 2020-05-07 10:29
Excellent! Let's move the discussion to Jira. Closing this here.

**Closed as completed by luksa** 2020-05-07 10:29 UTC
